kind = "web"
previewPath = "/"
title = "Little Caesars Pizza Parián"
version = "1.0.0"
id = "artifacts/little-caesars-parian"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20951

[services.development]
run = "pnpm --filter @workspace/little-caesars-parian run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/little-caesars-parian", "run", "build" ]
publicDir = "artifacts/little-caesars-parian/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20951"
BASE_PATH = "/"
